const dictionary = {
  'eng': {
    'contacts':'Contacts',
    'summary':'Summary',
    'skills':'Skills',
    'code':'Code',
    'education':'Education',
    'languages':'Languages',
    'projects':'Projects',
    'theme':'Theme',
    'light':'LIGHT',
    'dark':'DARK',
    'language':'language',
    'eng':'ENG',
    'rus':'RUS',
    'bel':'BEL',
    'name':'Semion Krapivin',
    'profession':'Junior Front-end developer',
    'contacts':'Contacts',
    'adress':'Minsk, Belarus',
    'skills':'Skills',
    'about':'About me',
    'about-text':`I'm 25 years old design engineer in energy producing industry. 
    I'm new to front-end development, I'm here to test my strength and motivation in a new profession.`,
    'strenghts':'My strenghts:',
    'strenght1':'Good communication skills',
    'strenght2':'Skill to work in team',
    'strenght3':'Responsibility',
    'strenght4':'Dependability',
    'strenght5':'Great willing to learn and develop new skills',
    'education':'Education',
    'college':'College',
    'college-text':'Minsk State Architectural and Сonstruction college, Industrial and Civil Construction major',
    'university':'University',
    'university-text':'National Technical University, Power Plants Engineering major',
    'courses':'Courses',
    'courses3':'BNTU Tecnical English course',
    'code':'Code example',
    'languages':'Languages',
    'language1':'English - A2',
    'language2':'Belarusian - Native',
    'language3':'Russian - Native',
    'projects':'Projects',
    'credits':'© 2021 Semion Krapivin'
  },

}